name: flutter_base_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+19

environment:
  sdk: '>=3.0.0 <4.0.0'
  #TODO: 3.0.0 and sdk 3.13.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.3.3
  gradient_borders: ^1.0.0
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  dotted_line: ^3.2.2
  dropdown_button2: ^2.3.9
  carousel_slider: ^4.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.0.15
  camera: ^0.10.5+5
  dartz: ^0.10.1
  logger: ^2.0.2+1
  modal_progress_hud_nsn: ^0.4.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1
  text_scroll: ^0.2.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_keyboard_visibility: ^5.4.1
  package_info_plus: ^4.2.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  firebase_messaging: ^14.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf